version: '3'

volumes:
  django_sample_db_dev: {}

services:
  mariadbproject:
    image: mariadb:10.4.18
    volumes:
      - django_sample_db_dev:/var/lib/mariadb/data
    environment:
      - MYSQL_DATABASE=icango
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=applemango00
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "3306:3306"

  djangoproject:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=mariadbproject
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=mariadbproject
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=applemango00
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0:8000 && docke exec -it && icango-back_djangoproject_1 bash"
    volumes:
      - ./:/code
    depends_on:
      - mariadbproject